server:
  port: 8080
spring:
  application:
    name: LargeOrangeShopping
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: 012089
